### ISSUE TITLE
Unable to use with node v0.12

### ISSUE THREAD

**Issue by Joshua-F** [emartech/gulp-pug-lint#1]
https://github.com/emartech/gulp-jade-lint/blob/master/config_parser.js is causing an issue running node v0.12 and below(haven't tested any of the io.js versions).

```
$ gulp
E:\Users\Joshua\Documents\Development\Node\Dashboard\node_modules\gulp-jade-lint\config_parser.js:5
class ConfigParser {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\Users\Joshua\Documents\Development\Node\Dashboard\node_modules\gulp-jade-lint\index.js:7:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\Users\Joshua\Documents\Development\Node\Dashboard\tasks\lint.js:4:16)
    at Module._compile (module.js:460:26)
```

**Comment by sonicoder86** [comment]
With version 0.1.4 it is made ES5 compatible.
